@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.1.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Jan 03 17:04:02 -0600 2022
REM SW Build 3286242 on Wed Jul 28 13:10:47 MDT 2021
REM
REM IP Build 3279568 on Wed Jul 28 16:48:48 MDT 2021
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto 517952a871384743a1dcdc4885929c97 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot ESCOMIPS_behav xil_defaultlib.ESCOMIPS -log elaborate.log"
call xelab  -wto 517952a871384743a1dcdc4885929c97 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot ESCOMIPS_behav xil_defaultlib.ESCOMIPS -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
