webtalk_init -webtalk_dir C:/Users/Karina/Desktop/Octavo semestre/Arqui/ESCOMIPS/ESCOMIPS.sim/sim_1/behav/xsim/xsim.dir/TB_ESCOMIPS_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec 21 00:41:31 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3286242" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "cedc7670-1285-478f-a57e-73a1c4f9757f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "517952a871384743a1dcdc4885929c97" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3400G with Radeon Vega Graphics    " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3693 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.16_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7276_KB" -context "xsim\\usage"
webtalk_transmit -clientid 574844585 -regid "" -xml C:/Users/Karina/Desktop/Octavo semestre/Arqui/ESCOMIPS/ESCOMIPS.sim/sim_1/behav/xsim/xsim.dir/TB_ESCOMIPS_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Karina/Desktop/Octavo semestre/Arqui/ESCOMIPS/ESCOMIPS.sim/sim_1/behav/xsim/xsim.dir/TB_ESCOMIPS_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Karina/Desktop/Octavo semestre/Arqui/ESCOMIPS/ESCOMIPS.sim/sim_1/behav/xsim/xsim.dir/TB_ESCOMIPS_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
